menu:
  布客新知: /ixinzhi
  ACG资源: /acg
  其它教程: /misc
  公开课: /mooc
  开发者: /developer
  自由职业: https://github.com/apachecn/awesome-indie-zh
  关于: /about
  龙哥盟: http://www.flygon.net
  RSS: /atom.xml
  "fork me on github": https://github.com/it-ebooks/blog

sidebar: right
widgets:
- about
- support
- ad
- link
- gate
- account

# Duoshuo
duoshuo_shortname: fl-it-ebooks

fancybox: true

google_analytics:
rss: /atom.xml

google_site_verification: NCXVSqxqB-os803-VFMtIEd1SUNJVOIjctCfNYUwD0w
baidu_site_verification: 
icon: 